SP-6202-step-error
stackpulse/steps-sdk-go pull request #11
Opened 2021-05-11 13:21 UTC by talbe

2021-05-11 16:09 UTC, kostyay commented on step/error.go
> +	FailedPrecondition
not sure its relevant to steps

2021-05-11 16:09 UTC, kostyay commented on step/error.go
> +	Unimplemented
not sure its relevant to steps

2021-05-11 16:09 UTC, kostyay commented on step/error.go
> +const (
remove grpc related comments

2021-05-11 16:10 UTC, kostyay commented on step/error.go
> +	Internal
not sure its relevant to steps

2021-05-11 16:10 UTC, kostyay commented on step/error.go
> +	DataLoss
not sure its relevant to steps

2021-05-11 16:11 UTC, kostyay commented on step/step.go
> +	Run() (outputJson JSONOutput, stepError *Error)
named parameters are not needed, its self explanatory
```suggestion
	Run() JSONOutput, stepError *Error
```

2021-05-11 16:12 UTC, kostyay commented on step/error.go
> +	Verbose string
add `json:` tags

2021-05-11 16:13 UTC, kostyay commented on step/step.go
> +	container.Set(spError.Code, "step_error", "code")
is there a way to do it more elegantly? can u somehow use the tags defined in Error?

2021-05-11 16:15 UTC, kostyay commented on step/step.go
> +	}
why unmarshal twice? once with json.Unmarshal and then with gabs?

2021-05-11 16:16 UTC, kostyay commented on step/step.go
> +		printOutput(JSONContainer)
you can move this code to defer as it keeps repeating itself

2021-05-11 16:17 UTC, kostyay commented on step/step.go
> +
```suggestion
var stepError *Error
defer func() {
    if stepError == nil {
        return
    }
    
    injectStepError(JSONContainer, stepError)
    printOutput(JSONContainer)
}()
```

2021-05-11 16:17 UTC, kostyay commented on step/step.go
> +		printOutput(JSONContainer)
defer

2021-05-11 16:18 UTC, kostyay commented on step/step.go
> +	JSONContainer := gabs.New()
```suggestion
	output := gabs.New()
```

2021-05-11 16:19 UTC, kostyay commented on step/step.go
> +	return nil
return stepError

2021-05-12 05:13 UTC, talbe commented on step/error.go
> +	OutOfRange
Actually this is make sense.. there will be cases where step would try to access out of range object

2021-05-12 07:43 UTC, alongat commented on step/step.go
> +	stepErrorContainer, _ := gabs.ParseJSON(stepErrorJSON)
Why do we need gabs?
If stepOutput was parsed as json, you can just
```
stepOutput['step_error'] = stepError
```

2021-05-12 07:44 UTC, alongat commented on step/step.go
> +	_, err = errorContainer.Set(stepErrorContainer, "step_error")
step_error -> const

2021-05-12 08:45 UTC, alongat commented on step/step_test.go
> +	"github.com/Jeffail/gabs/v2"
?

2021-05-12 08:46 UTC, alongat commented on step/step.go
> +
\n

2021-05-12 08:48 UTC, alongat commented on step/step.go
> +			Message: "success",
const

2021-05-12 08:49 UTC, alongat commented on step/step.go
> +			Message: "something went wrong. can't parse step output",
const

2021-05-12 08:49 UTC, alongat commented on step/step.go
> +	printOutput(stepOutput, &Error{Code: OK, Message: "success"})
const

2021-05-12 08:56 UTC, alongat approved these changes
💪 
See small comments

2021-05-12 14:07 UTC, kostyay commented on step/error.go
> +	// Note that this differs from FailedPrecondition. It indicates arguments
remove references in comments to FailedPrecondition

2021-05-12 14:08 UTC, kostyay commented on step/error.go
> +	// See litmus test above for deciding between FailedPrecondition,
FailedPrecondition

2021-05-12 14:08 UTC, kostyay commented on step/error.go
> +const (
review comments again and make sure they are relevant and dont refer to unrelated values

2021-05-12 14:11 UTC, kostyay commented on step/step.go
> +			Code:    InvalidArgument,
i think this is actually "Internal Error" so perhaps adding an internal status makes sense?
invalid argument is when a given argument to the step has invalid value

2021-05-12 14:14 UTC, kostyay commented on step/step.go
> +	os.Stdout.Write([]byte(fmt.Sprintf("%s%s", env.EndMarkerDefault, JSONStepOutput)))
more efficient in this case
```suggestion
	os.Stdout.Write([]byte(env.EndMarkerDefault + jsonStepOutput))
```

2021-05-12 14:16 UTC, kostyay commented on step/step.go
> +		stepError = &Error{
whats the point of this? this wont be printed/shown anywhere

2021-05-12 14:16 UTC, kostyay commented on step/step.go
> +func printOutput(stepOutput map[string]interface{}, stepError *Error) {
```suggestion
func printOutput(stepOutput map[string]interface{}, stepError *Error) error {
```

the function should return an error so run can return `ExitCodeFailure` if the marshalling fails

2021-05-12 14:17 UTC, kostyay commented on step/step.go
> +func printOutput(stepOutput map[string]interface{}, stepError *Error) {
```suggestion
var ErrSuccess = &Error{
			Code:    OK,
			Message: "success"}
func printOutput(stepOutput map[string]interface{}, stepError *Error) {
```

2021-05-12 14:26 UTC, kostyay requested changes
see some more comments

2021-05-12 14:26 UTC, kostyay commented on step/step.go
> +	Init() *Error
maybe return `Error` everywhere instead of `*Error`.. looks kinda better
WDYT?

2021-05-12 14:26 UTC, kostyay commented on step/step.go
> +	printOutput(stepOutput, &Error{Code: OK, Message: "success"})
```suggestion
	if err := printOutput(stepOutput, &Error{Code: OK, Message: "success"}); err != nil {
	    return fmt.Errorf("print output: %w", err)
	}
```

2021-05-12 14:26 UTC, kostyay commented on step/step_test.go
> +	successJSON := "{ \"success\": \"true\" }"
```suggestion
	successJSON := `{ "success": "true" }`
```

2021-05-12 14:26 UTC, kostyay commented on step/step.go
> +type JSONOutput map[string]interface{}
```suggestion
type Output map[string]interface{}
```

why not just Output? JSONOutput is confusing since its not really json but a `map[string]interface{}`

2021-05-12 14:26 UTC, kostyay commented on step/step.go
> +		stepOutput = map[string]interface{}{}
```suggestion
		stepOutput = Output{}
```

2021-05-12 14:26 UTC, kostyay commented on step/step.go
> +	}
```suggestion
	if err := step.Init(); err != nil {
		printOutput(Output{}, err)
		return err
	}

	stepOutput, err := step.Run()
	if err != nil {
		printOutput(stepOutput, err)
		return err
	}
```

2021-05-12 14:26 UTC, kostyay commented on step/step.go
> +	}
lets stick to go conventions called errors `err`

2021-05-12 14:40 UTC, talbe commented on step/step.go
> +	Init() *Error
I pretty like this way, because then you can check if the error is not nil

2021-05-12 14:49 UTC, talbe commented on step/step.go
> +		stepError = &Error{
it will.. we always injecting step_error object

2021-05-12 15:16 UTC, kostyay commented on step/error.go
> +	// caused by exhausting some resource (use ResourceExhausted
remove reference to ResourceExhausted

2021-05-12 15:17 UTC, kostyay commented on step/step.go
>  type Outputs struct {
i dont think this is used anywhere? can u check and remove if not needed

2021-05-12 15:17 UTC, kostyay commented on step/step.go
> +}
move to error.go

2021-05-12 15:19 UTC, kostyay commented on step/step.go
> +		if err := printOutput(map[string]interface{}{}, stepError); err != nil {
```suggestion
		if err := printOutput(nil, stepError); err != nil {
```
your function handles nil properly

2021-05-12 15:28 UTC, kostyay commented on step/step.go
> +func Run(step Step) error {
```go
func runStep(step Step) (Output, *Error) {
	if err := step.Init(); err != nil {
		return nil, err
	}

	return step.Run()
}

func Run(step Step) error {
    stepOutput, stepError = runStep(step)
	if err := printOutput(stepOutput, stepError); err != nil {
		return fmt.Errorf("print output: %w", err)
	}

	return nil
}
```

2021-05-12 15:28 UTC, kostyay reviewed
see comments

2021-05-12 15:39 UTC, talbe commented on step/step.go
>  type Outputs struct {
There are steps that are using this
![image](https://user-images.githubusercontent.com/7290571/118003570-5ed9ff80-b351-11eb-9df5-3869968a3641.png)

2021-05-12 15:52 UTC, kostyay commented on step/step.go
> +		os.Stdout.Write([]byte(env.EndMarkerDefault + string(jsonStepOutput)))
jsonStepOutput is invalid in this case. just return error here without all the extra code

2021-05-12 15:53 UTC, kostyay commented on step/step.go
> +		stepError = &Error{
```suggestion

```

2021-05-12 15:53 UTC, kostyay commented on step/step.go
> +			Verbose: fmt.Errorf("error: %w", err).Error(),
```suggestion

```

2021-05-12 15:53 UTC, kostyay commented on step/step.go
> +		os.Stdout.Write([]byte(env.EndMarkerDefault + string(jsonStepOutput)))
```suggestion

```

2021-05-12 15:54 UTC, kostyay commented on step/step.go
> +	badOutputParse = "something went wrong. can't parse step output"
```suggestion
```
dont need this

2021-05-12 15:56 UTC, kostyay approved these changes
fix comments and merge

2021-05-12 15:56 UTC, kostyay commented on step/step_test.go
> +func TestParseKeyPairEnv(t *testing.T) {
`TestParseKeyPairEnv`? copy paste? give better name

2021-05-12 15:57 UTC, kostyay commented
fix comments and merge

2021-05-12 18:16 UTC, merged