add upload for rich output file
stackpulse/steps-sdk-go pull request #4
Opened 2021-04-12 10:14 UTC by talbe

2021-04-12 10:39 UTC, talbe commented on output/output.go
> +	req, err := http.NewRequestWithContext(ctx, http.MethodPut, os.Getenv(RichOutputURL), content)
Not sure about the os.Getenv - WDYT?

2021-04-13 07:42 UTC, kostyay requested changes
see comments + add a test

2021-04-13 07:42 UTC, kostyay commented on output/output.go
> +func UploadRichOutputFile(ctx context.Context, content io.Reader, contentType int) error {
```suggestion
func Upload(ctx context.Context, dst string, contentType ContentType, content io.Reader) error {
```

2021-04-13 07:42 UTC, kostyay commented on output/output.go
> +		return fmt.Errorf("upload rich output file: bad content type %d", contentType)
```suggestion
		return fmt.Errorf("invalid content type %d", contentType)
```

2021-04-13 07:42 UTC, kostyay commented on output/output.go
> +	req, err := http.NewRequestWithContext(ctx, http.MethodPut, os.Getenv(RichOutputURL), content)
> Not sure about the os.Getenv - WDYT?

```suggestion
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, dst, content)
```

2021-04-13 07:42 UTC, kostyay commented on output/output.go
> +		return fmt.Errorf("upload rich output file: %w", err)
```suggestion
		return fmt.Errorf("new http request: %w", err)
```

2021-04-13 07:42 UTC, kostyay commented on output/output.go
> +		return fmt.Errorf("upload rich output file: %w", err)
```suggestion
		return fmt.Errorf("upload: %w", err)
```

2021-04-13 07:42 UTC, kostyay commented on output/output.go
> +	RichOutputURL = "RICH_OUTPUT_URL"
```suggestion
	envRichOutputURL = "RICH_OUTPUT_URL"
```

2021-04-13 07:42 UTC, kostyay commented on output/output.go
> +
```go
func UploadRichOutput(ctx context.Context,  t ContentType, content io.Reader) error {
    outputDst := os.Getenv(envRichOutputURL)
    if outputDst == "" {
        return error
    }
    return Upload(ctx, os.Getenv(envRichOutputURL), contentType, content)
}
```

2021-04-13 08:12 UTC, alongat commented on output/output.go
> +	ContentTypeMarkdown = 6
Keep only the data we currently fully support

2021-04-13 10:28 UTC, oriser commented on output/output.go
> +
Check the status code of the response here.
The http can return no error, but the status should be 20X (StatusCode/100 == 2)

2021-04-13 11:56 UTC, kostyay approved these changes

2021-04-13 11:56 UTC, kostyay commented on upload/upload.go
> +	richOutputURL, ok := os.LookupEnv(envRichOutputURL)
check richOutputURL != ""

2021-04-13 11:56 UTC, kostyay commented on upload/upload.go
> +	if resp.StatusCode/2 != 2 {
```suggestion
	if resp.StatusCode/100 != 2 {
```

2021-04-13 11:56 UTC, kostyay commented
see comment + add test

2021-04-13 13:54 UTC, oriser commented on upload/upload.go
> +}
noice

2021-04-14 06:16 UTC, vic3lord commented on upload/upload.go
> +	defer resp.Body.Close()
```suggestion
	}	
	defer resp.Body.Close()
	
	if resp.StatusCode/100 != 2 {
		return fmt.Errorf("bad http status code receieved: %d", resp.StatusCode)
	}
```

2021-04-14 06:24 UTC, vic3lord commented on upload/upload.go
> +	defer resp.Body.Close()
Usually the `defer` comes first, right after the error of the action you tried to do 

Example: 

os.Open(file)
if err != nil {
}
defer f.Close()

2021-04-18 11:16 UTC, merged